# Generated by Django 5.0.2 on 2024-04-02 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tripdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripnumber', models.TextField()),
                ('drivername', models.TextField()),
                ('guestname', models.TextField()),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('startkm', models.IntegerField()),
                ('endkm', models.IntegerField()),
                ('vehiclename', models.TextField()),
                ('vehiclenumber', models.TextField()),
                ('parking', models.IntegerField()),
                ('toll', models.IntegerField()),
                ('tripkm', models.IntegerField()),
                ('total', models.IntegerField()),
                ('advance', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('fixed', models.IntegerField()),
                ('extra', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
