# Generated by Django 5.0.2 on 2024-04-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tripdata_todate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdata',
            name='fromdate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='todate',
            field=models.TextField(null=True),
        ),
    ]
