# Generated by Django 5.0.2 on 2024-04-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tripdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdata',
            name='advance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='drivername',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='end',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='endkm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='extra',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='fixed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='fromdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='guestname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='parking',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='start',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='startkm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='todate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='toll',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='tripkm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='tripnumber',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='vehiclename',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='vehiclenumber',
            field=models.TextField(null=True),
        ),
    ]
