# Generated by Django 5.0.2 on 2024-04-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tripdata_fromdate_alter_tripdata_todate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripdata',
            old_name='extra',
            new_name='guidecharge',
        ),
        migrations.RenameField(
            model_name='tripdata',
            old_name='fixed',
            new_name='tripcharge',
        ),
    ]
