# Generated by Django 5.0.2 on 2024-04-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tripdata_advance_alter_tripdata_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdata',
            name='advance',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='balance',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='endkm',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='extra',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='fixed',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='fromdate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='parking',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='startkm',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='todate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='toll',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='total',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tripdata',
            name='tripkm',
            field=models.TextField(null=True),
        ),
    ]
