# Generated by Django 5.0.2 on 2024-04-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_extra_tripdata_guidecharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdata',
            name='extra',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tripdata',
            name='huncharge',
            field=models.TextField(null=True),
        ),
    ]
