# Generated by Django 5.0.2 on 2024-04-15 07:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tripdata_other_guide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='guide',
            new_name='guidemod',
        ),
    ]
