# Generated by Django 5.0.2 on 2024-04-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_guide_guidemod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidemod',
            name='user',
        ),
        migrations.AddField(
            model_name='guidemod',
            name='tripno',
            field=models.TextField(null=True),
        ),
    ]
