# Generated by Django 5.0.2 on 2024-05-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_guidemod_user_othercharge_parkingcharge_tollcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercharge',
            name='charge',
            field=models.TextField(default=0),
        ),
    ]
