# Generated by Django 5.0.2 on 2024-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_parkingcharge_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingcharge',
            name='charge',
            field=models.TextField(),
        ),
    ]
