# Generated by Django 5.0.2 on 2024-05-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_charge_parkingcharge_pcharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othercharge',
            old_name='charge',
            new_name='ocharge',
        ),
        migrations.RenameField(
            model_name='tollcharge',
            old_name='charge',
            new_name='tcharge',
        ),
    ]
