# Generated by Django 5.0.2 on 2024-05-02 16:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_charge_othercharge_ocharge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='othercharge',
            new_name='othercharges',
        ),
    ]
