# Generated by Django 5.0.2 on 2024-05-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_parkingcharge_parkingcharges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingcharges',
            old_name='pcharge',
            new_name='zcharge',
        ),
    ]
