# Generated by Django 5.0.2 on 2024-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_charge_guidemod_guidecharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingcharges',
            name='park',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='parkingcharges',
            name='tripno',
            field=models.TextField(),
        ),
    ]
