# Generated by Django 5.0.2 on 2024-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_parkingcharges_park_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingcharges',
            name='park',
            field=models.IntegerField(),
        ),
    ]
